### ISSUE TITLE
Corrupt file, says Firefox

### ISSUE THREAD

**Issue by hueychen27** [OneShot-Niko/Imgflip-Redirect#1]
When I load the extension into Firefox, it says it is corrupt.
`File /home/horsey_guy/Downloads/Imgflip-Redirect-mv3.zip does not contain a valid manifest`
I'll still post this issue anyway even though the README.md file already says this.
My Firefox is version 115, so manifest version 3 should work.

**Comment by hueychen27** [comment]
Maybe run "web-ext sign" to make an .xpi file, but you need a Mozilla account and an API key.

**Comment by hueychen27** [comment]
I found the fix. In the zip file, it contains a folder. It should not contain a folder with all the files, just the files.

**Comment by hueychen27** [comment]
[imgflip_redirect.zip](https://github.com/OneShot-Niko/Imgflip-Redirect/files/13805778/imgflip_redirect.zip)

**Comment by OneShot-Niko** [comment]
Apologies for not seeing this - Have you extracted the zip before trying to open the manifest?
I could never open it without it being extracted, so just making usre.

**Comment by hueychen27** [comment]
I extracted it and compressed the files, not the folder.

**Comment by OneShot-Niko** [comment]
> I extracted it and compressed the files, not the folder.

Guessing that might've been it.
Unsure though since it loads fine for me even that way.

**Comment by hueychen27** [comment]
I used the file here: https://github.com/OneShot-Niko/Imgflip-Redirect/releases/tag/v1.0.1

**Comment by OneShot-Niko** [comment]
> I used the file here: https://github.com/OneShot-Niko/Imgflip-Redirect/releases/tag/v1.0.1

That release should work fine last time I tried

Also - Pretty sure this isn't an issue since the error you gave originally is a zip file which wasn't extracted

**Comment by hueychen27** [comment]
I extracted it and then compressed just the files to a zip format. That worked.

**Comment by OneShot-Niko** [comment]
> I extracted it and then compressed just the files to a zip format. That worked.

Yeah I'm unfortunately unsure then

**Comment by hueychen27** [comment]
ok

**Comment by hueychen27** [comment]
Also, how did you compress the file to a zip? Deflate method is the only one that works by running `zip thing` meaning that the compression type is probably not an issue.
